server:
  port: 8082
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
spring:
  thymeleaf:
    cache: false
spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
